version: '3'

services:
  pythonflask:
    image: pythonflask:latest
    ports:
      - "8010:8010"

  services_db:
    image: postgres
    ports:
      - "8009:5432"
    volumes:
      - /Users/nicolascorchuelo/data/db_pg:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
