FROM python:3.11.5

USER root
RUN pip install --upgrade pip
RUN apt-get update && \
    apt-get install net-tools

WORKDIR /fast-app

COPY requirements.txt .
ADD etl_api_call.py .
ADD connections.py .
ADD etl.py .
ADD static/swagger.json ./static/swagger.json
ADD source/source_sql/* .source/source_sql/
ADD source/*.csv ./source/

RUN pip install -r requirements.txt

CMD [ "python", "./etl_api_call.py"]